/* ============ 常用主要海港 UN/LOCODE 预筛子集（供自动补全） ============
   完整 UN/LOCODE 全表约 6.95MB，这里预筛主流国际港（约 60 个），体积小、可离线、可扩充。
   结构：{ code:"国家+城市3位", city, cn 中文名, country }。仅作录入辅助，非官方全量。 */
window.FTE_PORTS = [
  { code: "CNHKG", city: "Hong Kong", cn: "香港", country: "CN" },
  { code: "CNSHA", city: "Shanghai", cn: "上海", country: "CN" },
  { code: "CNNGB", city: "Ningbo", cn: "宁波", country: "CN" },
  { code: "CNSZX", city: "Shenzhen", cn: "深圳", country: "CN" },
  { code: "CNYTN", city: "Yantian", cn: "盐田", country: "CN" },
  { code: "CNGZG", city: "Guangzhou", cn: "广州", country: "CN" },
  { code: "CNXMN", city: "Xiamen", cn: "厦门", country: "CN" },
  { code: "CNTAO", city: "Qingdao", cn: "青岛", country: "CN" },
  { code: "CNDLC", city: "Dalian", cn: "大连", country: "CN" },
  { code: "CNTJG", city: "Tianjin (Xingang)", cn: "天津新港", country: "CN" },
  { code: "SGSIN", city: "Singapore", cn: "新加坡", country: "SG" },
  { code: "NLRTM", city: "Rotterdam", cn: "鹿特丹", country: "NL" },
  { code: "DEHAM", city: "Hamburg", cn: "汉堡", country: "DE" },
  { code: "DEBRV", city: "Bremerhaven", cn: "不来梅哈芬", country: "DE" },
  { code: "BEANR", city: "Antwerp", cn: "安特卫普", country: "BE" },
  { code: "GBFXT", city: "Felixstowe", cn: "费利克斯托", country: "GB" },
  { code: "GBSTH", city: "Southampton", cn: "南安普顿", country: "GB" },
  { code: "FRLPH", city: "Le Havre", cn: "勒阿弗尔", country: "FR" },
  { code: "ITGOA", city: "Genoa", cn: "热那亚", country: "IT" },
  { code: "ITNAP", city: "Naples", cn: "那不勒斯", country: "IT" },
  { code: "ESBCN", city: "Barcelona", cn: "巴塞罗那", country: "ES" },
  { code: "ESVLC", city: "Valencia", cn: "瓦伦西亚", country: "ES" },
  { code: "ESALG", city: "Algeciras", cn: "阿尔赫西拉斯", country: "ES" },
  { code: "PTLIS", city: "Lisbon", cn: "里斯本", country: "PT" },
  { code: "AEJEA", city: "Jebel Ali (Dubai)", cn: "杰贝阿里（迪拜）", country: "AE" },
  { code: "AEKHL", city: "Khalifa Port", cn: "哈里发港", country: "AE" },
  { code: "OPSHH", city: "Sharjah", cn: "沙迦", country: "AE" },
  { code: "INSHA", city: "Nhava Sheva (Mumbai)", cn: "那瓦舍瓦（孟买）", country: "IN" },
  { code: "INMAA", city: "Chennai (Madras)", cn: "金奈", country: "IN" },
  { code: "INCAL", city: "Kolkata", cn: "加尔各答", country: "IN" },
  { code: "JPTYO", city: "Tokyo", cn: "东京", country: "JP" },
  { code: "JPOSA", city: "Osaka", cn: "大阪", country: "JP" },
  { code: "JPUKB", city: "Kobe", cn: "神户", country: "JP" },
  { code: "KRPUS", city: "Busan", cn: "釜山", country: "KR" },
  { code: "KRINC", city: "Incheon", cn: "仁川", country: "KR" },
  { code: "VNSGN", city: "Ho Chi Minh", cn: "胡志明", country: "VN" },
  { code: "VNHPH", city: "Haiphong", cn: "海防", country: "VN" },
  { code: "THLCH", city: "Laem Chabang", cn: "林查班", country: "TH" },
  { code: "THBKK", city: "Bangkok", cn: "曼谷", country: "TH" },
  { code: "MYTPP", city: "Tanjung Pelepas", cn: "丹戎帕拉帕斯", country: "MY" },
  { code: "MYPKG", city: "Port Klang", cn: "巴生港", country: "MY" },
  { code: "PHSIN", city: "Manila", cn: "马尼拉", country: "PH" },
  { code: "IDJKT", city: "Jakarta (Tanjung Priok)", cn: "雅加达", country: "ID" },
  { code: "AUSYD", city: "Sydney", cn: "悉尼", country: "AU" },
  { code: "AUMEL", city: "Melbourne", cn: "墨尔本", country: "AU" },
  { code: "NZAKL", city: "Auckland", cn: "奥克兰", country: "NZ" },
  { code: "CAVAN", city: "Vancouver", cn: "温哥华", country: "CA" },
  { code: "CAPRR", city: "Prince Rupert", cn: "鲁珀特王子港", country: "CA" },
  { code: "USLAX", city: "Los Angeles", cn: "洛杉矶", country: "US" },
  { code: "USLGB", city: "Long Beach", cn: "长滩", country: "US" },
  { code: "USSEA", city: "Seattle", cn: "西雅图", country: "US" },
  { code: "USNYC", city: "New York", cn: "纽约", country: "US" },
  { code: "USSAV", city: "Savannah", cn: "萨凡纳", country: "US" },
  { code: "USMIA", city: "Miami", cn: "迈阿密", country: "US" },
  { code: "USCHI", city: "Chicago", cn: "芝加哥", country: "US" },
  { code: "BRSVZ", city: "Santos", cn: "桑托斯", country: "BR" },
  { code: "ARBUE", city: "Buenos Aires", cn: "布宜诺斯艾利斯", country: "AR" },
  { code: "CLSAI", city: "San Antonio", cn: "圣安东尼奥", country: "CL" },
  { code: "RULED", city: "St. Petersburg", cn: "圣彼得堡", country: "RU" },
  { code: "PLGDN", city: "Gdansk", cn: "格但斯克", country: "PL" },
  { code: "TRYIL", city: "Istanbul (Ambarli)", cn: "伊斯坦布尔", country: "TR" },
  { code: "EGSKH", city: "Sokhna", cn: "苏赫纳", country: "EG" },
  { code: "ZADUR", city: "Durban", cn: "德班", country: "ZA" }
];
