/* ============ 单元 15：货款回收、票据与海运保险（追加到 FTE_DATA.units） ============ */
(function () {
  "use strict";
  if (typeof FTE_DATA === "undefined" || !FTE_DATA || !FTE_DATA.units) return;
  FTE_DATA.units.push({
    id: 15,
    title: "货款回收、票据与海运保险",
    titleEn: "Payment Collection, Instruments & Marine Insurance",
    icon: "🏦",
    summary: "软包装出口的收款环节：电汇、托收与信用证三类结算方式的流程与风险，汇票本票支票等票据术语，海运保险险别、保单与索赔表达——谈付款条件、审证与处理不符点时把话说准。",
    vocab: [
      { w: "remittance", ipa: "/rɪˈmɪtəns/", pos: "n.", cn: "汇款、汇付（remit 的名词形式）", ex: "Your remittance of USD 18,600 for the laminating adhesive has been credited to our account.", exCn: "您支付复膜胶货款 18,600 美元的汇款已入我方账户。" },
      { w: "telegraphic transfer", ipa: "/ˌtelɪˈɡræfɪk ˈtrænsfɜːr/", pos: "n.", cn: "电汇（T/T）", ex: "We accept a 30% deposit by telegraphic transfer and the balance against the copy B/L.", exCn: "我们接受电汇 30% 定金，余款凭提单副本支付。" },
      { w: "mail transfer", ipa: "/meɪl ˈtrænsfɜːr/", pos: "n.", cn: "信汇（M/T，邮寄委托书汇款）", ex: "Mail transfer is far too slow for this order, so please arrange a T/T instead.", exCn: "这笔订单用信汇太慢，请改安排电汇。" },
      { w: "demand draft", ipa: "/dɪˈmɑːnd drɑːft/", pos: "n.", cn: "票汇（D/D，即期银行汇票）", ex: "The buyer settled the sample charge by a demand draft drawn on a bank in Singapore.", exCn: "买方用一张开在新加坡某银行的票汇支付了样品费。" },
      { w: "collection", ipa: "/kəˈlekʃn/", pos: "n.", cn: "托收（银行代收货款）", ex: "Under collection the bank only handles the documents and assumes no payment liability.", exCn: "托收项下银行只负责处理单据，不承担付款责任。" },
      { w: "documents against payment", ipa: "/ˈdɑːkjumənts əˈɡenst ˈpeɪmənt/", pos: "n.", cn: "付款交单（D/P）", ex: "For this trial order of BOPP film we can only work on documents against payment at sight.", exCn: "这批 BOPP 薄膜试单我们只能做即期付款交单。" },
      { w: "documents against acceptance", ipa: "/ˈdɑːkjumənts əˈɡenst əkˈseptəns/", pos: "n.", cn: "承兑交单（D/A）", ex: "Documents against acceptance means the buyer gets the documents merely by accepting the draft.", exCn: "承兑交单意味着买方只要承兑汇票就能拿到单据。" },
      { w: "letter of credit", ipa: "/ˈletər əv ˈkredɪt/", pos: "n.", cn: "信用证（L/C）", ex: "Please open an irrevocable letter of credit at sight before the end of this month.", exCn: "请在本月底前开出不可撤销即期信用证。" },
      { w: "documentary credit", ipa: "/ˌdɑːkjuˈmentri ˈkredɪt/", pos: "n.", cn: "跟单信用证（documentary credit，即凭单付款的信用证）", ex: "A documentary credit is payable only when the stipulated documents are presented in order.", exCn: "跟单信用证只有在规定单据相符交单时才付款。" },
      { w: "irrevocable", ipa: "/ɪˈrevəkəbl/", pos: "adj.", cn: "不可撤销的（不可撤销信用证 irrevocable L/C）", ex: "An irrevocable credit cannot be cancelled or amended without the beneficiary consent.", exCn: "不可撤销信用证未经受益人同意不得撤销或修改。" },
      { w: "revocable", ipa: "/ˈrevəkəbl/", pos: "adj.", cn: "可撤销的（可撤销信用证 revocable L/C）", ex: "We never ship against a revocable credit because the issuing bank may withdraw it anytime.", exCn: "我们从不凭可撤销信用证发货，因为开证行随时可以撤销。" },
      { w: "confirmed L/C", ipa: "/kənˈfɜːmd ˌel ˈsiː/", pos: "n.", cn: "保兑信用证（由第三家银行加具保兑）", ex: "As the issuing bank is small, we ask for a confirmed L/C added by a prime bank.", exCn: "由于开证行规模很小，我们要求由一流银行加具保兑。" },
      { w: "sight L/C", ipa: "/saɪt ˌel ˈsiː/", pos: "n.", cn: "即期信用证（见票即付）", ex: "Under a sight L/C we get paid within five banking days after clean documents are presented.", exCn: "即期信用证项下相符交单后五个银行工作日内我们即可收款。" },
      { w: "usance L/C", ipa: "/ˈjuːzns ˌel ˈsiː/", pos: "n.", cn: "远期信用证（usance L/C，如 60 天期）", ex: "A 90-day usance L/C ties up our cash flow, so a sight credit is strongly preferred.", exCn: "90 天远期信用证会占用我们的资金，因此我们更希望用即期证。" },
      { w: "transferable L/C", ipa: "/trænsˈfɜːrəbl ˌel ˈsiː/", pos: "n.", cn: "可转让信用证（受益人可转让给第二受益人）", ex: "The trading company asked for a transferable L/C so that it could pay the film mill directly.", exCn: "贸易公司要求开可转让信用证，以便直接向薄膜厂付款。" },
      { w: "revolving L/C", ipa: "/rɪˈvɑːlvɪŋ ˌel ˈsiː/", pos: "n.", cn: "循环信用证（金额可循环使用）", ex: "For monthly shipments of pouches a revolving L/C saves both sides a lot of bank charges.", exCn: "包装袋按月出货时，循环信用证能为双方省下不少银行费用。" },
      { w: "back-to-back L/C", ipa: "/ˌbæk tə ˈbæk ˌel ˈsiː/", pos: "n.", cn: "背对背信用证（对背信用证）", ex: "The agent opened a back-to-back L/C in our favour on the strength of the master credit.", exCn: "代理商凭主信用证以我方为受益人开出了背对背信用证。" },
      { w: "standby L/C", ipa: "/ˈstændbaɪ ˌel ˈsiː/", pos: "n.", cn: "备用信用证（担保性质，SBLC）", ex: "We can grant open account terms if the buyer provides a standby L/C as security.", exCn: "如买方提供备用信用证作担保，我们可以给赊销条件。" },
      { w: "soft clause", ipa: "/sɑːft klɔːz/", pos: "n.", cn: "软条款（陷阱条款）", ex: "This soft clause makes payment depend on an inspection certificate signed by the applicant.", exCn: "这条软条款使付款取决于开证申请人签署的检验证书。" },
      { w: "discrepancy", ipa: "/dɪˈskrepənsi/", pos: "n.", cn: "不符点（单据与信用证不一致之处）", ex: "The bank raised two discrepancies: a late shipment and a wrong description of the adhesive.", exCn: "银行提出两个不符点：迟装运和复膜胶品名描述错误。" },
      { w: "applicant", ipa: "/ˈæplɪkənt/", pos: "n.", cn: "开证申请人（进口方）", ex: "The applicant refused to amend the credit, so we had to ship within the original deadline.", exCn: "开证申请人拒绝改证，我们只能在原定期限内出货。" },
      { w: "beneficiary", ipa: "/ˌbenɪˈfɪʃəri/", pos: "n.", cn: "受益人（信用证收款方，通常是出口方）", ex: "Please make sure the beneficiary name matches our business licence letter for letter.", exCn: "请确保受益人名称与我方营业执照逐字一致。" },
      { w: "issuing bank", ipa: "/ˈɪʃuːɪŋ bæŋk/", pos: "n.", cn: "开证行（开立信用证的银行）", ex: "Our bank rates the issuing bank as high risk, so we need the credit confirmed.", exCn: "我方银行将该开证行评为高风险，因此我们需要加保兑。" },
      { w: "advising bank", ipa: "/ədˈvaɪzɪŋ bæŋk/", pos: "n.", cn: "通知行（核验并通知信用证的银行）", ex: "The advising bank notified us of the credit this morning together with the SWIFT copy.", exCn: "通知行今天上午连同 SWIFT 副本通知了我们该信用证。" },
      { w: "negotiating bank", ipa: "/nɪˈɡoʊʃieɪtɪŋ bæŋk/", pos: "n.", cn: "议付行（买入单据垫付货款的银行）", ex: "The negotiating bank advanced 95% of the invoice value against our clean documents.", exCn: "议付行凭我方相符单据垫付了发票金额的 95%。" },
      { w: "paying bank", ipa: "/ˈpeɪɪŋ bæŋk/", pos: "n.", cn: "付款行（信用证指定付款的银行）", ex: "The paying bank in Hamburg remitted the proceeds three days after receiving the documents.", exCn: "汉堡的付款行在收到单据三天后汇出了货款。" },
      { w: "bill of exchange", ipa: "/ˌbɪl əv ɪksˈtʃeɪndʒ/", pos: "n.", cn: "汇票（draft）", ex: "Kindly draw a bill of exchange in duplicate for the full invoice value of the pouches.", exCn: "请按包装袋发票全额开立汇票一套两份。" },
      { w: "drawer", ipa: "/ˈdrɔːər/", pos: "n.", cn: "出票人（开立汇票的人，通常为出口方）", ex: "As drawer of the draft, we sign it and present it through our bank for collection.", exCn: "作为汇票出票人，我们签署汇票并通过银行交单托收。" },
      { w: "drawee", ipa: "/drɔːˈiː/", pos: "n.", cn: "付款人、受票人（被要求付款的一方）", ex: "The drawee is the issuing bank, not the buyer, under this deferred payment credit.", exCn: "在这张延期付款信用证下，付款人是开证行而不是买方。" },
      { w: "payee", ipa: "/peɪˈiː/", pos: "n.", cn: "收款人（票据上受领款项的人）", ex: "Please show our company as the payee and keep the spelling exactly as in the contract.", exCn: "请把我公司列为收款人，拼写务必与合同完全一致。" },
      { w: "endorsement", ipa: "/ɪnˈdɔːsmənt/", pos: "n.", cn: "背书（在票据背面签署转让）", ex: "The bill of lading was made out to order and transferred by blank endorsement.", exCn: "该提单做成指示式，通过空白背书转让。" },
      { w: "acceptance", ipa: "/əkˈseptəns/", pos: "n.", cn: "承兑（承诺到期付款）", ex: "We released the documents only after the bank confirmed acceptance of the 60-day draft.", exCn: "只有在银行确认承兑 60 天期汇票后，我们才放单。" },
      { w: "presentation", ipa: "/ˌprezənˈteɪʃn/", pos: "n.", cn: "提示、交单（向银行提交单据）", ex: "Presentation must be made within 21 days after shipment but inside the credit validity.", exCn: "交单须在装运后 21 天内且在信用证有效期内完成。" },
      { w: "promissory note", ipa: "/ˈprɑːmɪsəri noʊt/", pos: "n.", cn: "本票（出票人自己承诺付款的票据）", ex: "The buyer offered a promissory note, but we prefer a bank guarantee for this amount.", exCn: "买方提出用本票，但这个金额我们更希望有银行保函。" },
      { w: "cheque", ipa: "/tʃek/", pos: "n.", cn: "支票（美式拼写 check）", ex: "A personal cheque is not acceptable for the deposit; please arrange a bank transfer.", exCn: "定金不接受私人支票，请安排银行转账。" },
      { w: "open account", ipa: "/ˌoʊpən əˈkaʊnt/", pos: "n.", cn: "赊销、记账交易（O/A）", ex: "Open account 60 days is only available to buyers covered by our credit insurance limit.", exCn: "O/A 60 天只提供给在我方信用保险限额内的买家。" },
      { w: "deposit", ipa: "/dɪˈpɑːzɪt/", pos: "n.", cn: "定金、订金（deposit）", ex: "Production will be scheduled only after the 30% deposit is received in our account.", exCn: "只有 30% 定金入账后才会安排排产。" },
      { w: "balance", ipa: "/ˈbæləns/", pos: "n.", cn: "余款、尾款（balance of payment）", ex: "The balance of 70% is payable against a scanned copy of the bill of lading.", exCn: "70% 尾款凭提单扫描副本支付。" },
      { w: "down payment", ipa: "/ˌdaʊn ˈpeɪmənt/", pos: "n.", cn: "首付款、预付款（首期付款）", ex: "A 40% down payment covers our raw film cost, so we cannot go any lower.", exCn: "40% 首付款刚够覆盖原膜成本，我们无法再降。" },
      { w: "credit investigation", ipa: "/ˈkredɪt ɪnˌvestɪˈɡeɪʃn/", pos: "n.", cn: "资信调查（credit check）", ex: "Our credit investigation shows the buyer has been sued twice for overdue payments.", exCn: "我们的资信调查显示该买家曾两次因逾期付款被起诉。" },
      { w: "export credit insurance", ipa: "/ˈekspɔːt ˈkredɪt ɪnˈʃʊərəns/", pos: "n.", cn: "出口信用保险（承保买方不付款风险）", ex: "Export credit insurance covers up to 90% of the loss if the buyer defaults.", exCn: "买方违约时，出口信用保险最高赔付损失的 90%。" },
      { w: "marine insurance", ipa: "/məˈriːn ɪnˈʃʊərəns/", pos: "n.", cn: "海运保险、水险（ocean marine insurance）", ex: "Under CIF we arrange marine insurance for 110% of the invoice value.", exCn: "CIF 条件下由我方按发票金额的 110% 投保海运保险。" },
      { w: "premium", ipa: "/ˈpriːmiəm/", pos: "n.", cn: "保险费（insurance premium）", ex: "The premium for All Risks on this pouch shipment is only 0.35% of the insured amount.", exCn: "这批包装袋投保一切险的保费仅为保额的 0.35%。" },
      { w: "insurance policy", ipa: "/ɪnˈʃʊərəns ˈpɑːləsi/", pos: "n.", cn: "保险单（正式保单）", ex: "The credit calls for an insurance policy in duplicate endorsed in blank.", exCn: "信用证要求提供一式两份空白背书的保险单。" },
      { w: "insurance certificate", ipa: "/ɪnˈʃʊərəns səˈtɪfɪkət/", pos: "n.", cn: "保险凭证（简式保险单据）", ex: "An insurance certificate is not acceptable here because the L/C stipulates a policy.", exCn: "此处不接受保险凭证，因为信用证规定必须是保险单。" },
      { w: "Free from Particular Average", ipa: "/ˌfriː frəm pəˈtɪkjələr ˈævərɪdʒ/", pos: "n.", cn: "平安险（FPA，不赔单独海损）", ex: "Free from Particular Average is too narrow for rolls of film stowed on deck.", exCn: "对于装在甲板上的薄膜卷，平安险的保障范围太窄。" },
      { w: "With Particular Average", ipa: "/wɪð pəˈtɪkjələr ˈævərɪdʒ/", pos: "n.", cn: "水渍险（WPA，赔单独海损）", ex: "With Particular Average also covers partial loss caused by heavy weather at sea.", exCn: "水渍险还承保海上恶劣气候造成的部分损失。" },
      { w: "All Risks", ipa: "/ˌɔːl ˈrɪsks/", pos: "n.", cn: "一切险（All Risks，含一般外来风险）", ex: "Please cover All Risks and War Risk from Ningbo to Rotterdam for this order.", exCn: "本单请投保宁波至鹿特丹的一切险及战争险。" },
      { w: "general average", ipa: "/ˌdʒenrəl ˈævərɪdʒ/", pos: "n.", cn: "共同海损（G.A.，各方分摊）", ex: "The cargo jettisoned to save the vessel was treated as general average.", exCn: "为救船而抛弃的货物被作为共同海损处理。" },
      { w: "particular average", ipa: "/pəˈtɪkjələr ˈævərɪdʒ/", pos: "n.", cn: "单独海损（P.A.，由货主自担或按险别赔）", ex: "Water damage to twelve cartons of laminated pouches is a particular average.", exCn: "十二箱复合包装袋的水湿损失属于单独海损。" },
      { w: "actual total loss", ipa: "/ˈæktʃuəl ˈtoʊtl lɑːs/", pos: "n.", cn: "实际全损（货物完全灭失）", ex: "The fire in the hold caused an actual total loss of the whole consignment.", exCn: "货舱火灾造成整批货物实际全损。" },
      { w: "constructive total loss", ipa: "/kənˈstrʌktɪv ˈtoʊtl lɑːs/", pos: "n.", cn: "推定全损（修复费用超过货值）", ex: "Since salvage would cost more than the goods, the underwriter declared a constructive total loss.", exCn: "由于救助费用超过货值，保险人宣布为推定全损。" },
      { w: "salvage charges", ipa: "/ˈsælvɪdʒ ˈtʃɑːdʒɪz/", pos: "n.", cn: "救助费用（施救报酬）", ex: "Salvage charges are recoverable under the policy provided the loss is insured.", exCn: "只要损失属承保范围，救助费用可在保单下获赔。" },
      { w: "claim", ipa: "/kleɪm/", pos: "n./v.", cn: "索赔（lodge a claim 提出索赔）", ex: "We lodged a claim for USD 4,200 supported by the survey report and packing list.", exCn: "我们凭检验报告和箱单提出了 4,200 美元的索赔。" },
      { w: "survey report", ipa: "/ˈsɜːveɪ rɪˈpɔːt/", pos: "n.", cn: "检验报告、公证报告（查勘报告）", ex: "No claim will be entertained without a survey report issued at the port of discharge.", exCn: "没有卸货港出具的检验报告，索赔不予受理。" }
    ],
    phrases: [
      { p: "open a letter of credit", cn: "开立信用证", ex: "Please open an irrevocable letter of credit at sight before the end of this month.", exCn: "请在本月底前开出不可撤销即期信用证。" },
      { p: "pay the balance against the copy B/L", cn: "凭提单副本支付尾款", ex: "You pay the balance against the copy B/L, and we release the originals the same day.", exCn: "您凭提单副本支付尾款，我们当天就放正本提单。" },
      { p: "amend the letter of credit", cn: "修改信用证", ex: "Kindly amend the letter of credit to delete the buyer inspection certificate clause.", exCn: "请修改信用证，删除买方检验证书条款。" },
      { p: "present documents for negotiation", cn: "交单议付", ex: "We presented documents for negotiation on the fifth day after the vessel sailed.", exCn: "船开后第五天我们就交单议付了。" },
      { p: "waive the discrepancies", cn: "接受（放弃追究）不符点", ex: "Could you instruct the issuing bank to waive the discrepancies and effect payment?", exCn: "能否请您指示开证行接受不符点并放款？" },
      { p: "cover insurance against All Risks", cn: "投保一切险", ex: "We will cover insurance against All Risks for 110% of the CIF value.", exCn: "我们将按 CIF 价的 110% 投保一切险。" },
      { p: "lodge a claim with the underwriter", cn: "向保险人提出索赔", ex: "Please lodge a claim with the underwriter within the time limit stated in the policy.", exCn: "请在保单规定的时限内向保险人提出索赔。" },
      { p: "extend the latest shipment date", cn: "展延最迟装运期", ex: "The raw film is delayed, so we have to ask you to extend the latest shipment date.", exCn: "原膜延误，我们不得不请您展延最迟装运期。" },
      { p: "accept the draft at 60 days after sight", cn: "承兑见票后 60 天付款的汇票", ex: "Your bank should accept the draft at 60 days after sight before we release the documents.", exCn: "您方银行应先承兑见票后 60 天付款的汇票，我们才放单。" },
      { p: "release the original bills of lading", cn: "放出正本提单", ex: "We can only release the original bills of lading once the full payment is confirmed.", exCn: "只有确认全额收款后我们才能放出正本提单。" },
      { p: "establish a credit limit for the buyer", cn: "为买家核定信用额度", ex: "The insurer has established a credit limit of USD 80,000 for this German buyer.", exCn: "保险公司已为这家德国买家核定 8 万美元信用额度。" },
      { p: "settle the payment by T/T", cn: "以电汇方式结算货款", ex: "Most of our regular clients settle the payment by T/T within three working days.", exCn: "我们多数老客户都在三个工作日内以电汇结清货款。" }
    ],
    dialogues: [
      {
        title: "谈付款方式（Negotiating Payment Terms）",
        lines: [
          { sp: "A", en: "About the payment terms for the 18 tons of laminating adhesive, we would like open account 60 days.", cn: "关于这 18 吨复膜胶的付款方式，我们希望做 O/A 60 天。" },
          { sp: "B", en: "I understand, but O/A 60 days is only for buyers with three years of clean payment records with us.", cn: "我理解，但 O/A 60 天只提供给与我们有三年良好付款记录的客户。" },
          { sp: "A", en: "This is our second order, and our other Chinese suppliers already give us 60 days.", cn: "这是我们的第二单，其他中国供应商已经给我们 60 天了。" },
          { sp: "B", en: "For a second order our standard is 30% deposit and 70% balance against the copy bill of lading.", cn: "第二单我们的标准是 30% 定金、70% 尾款凭提单副本支付。" },
          { sp: "A", en: "Our cash flow is tight because our own customers pay us only after they use up the film.", cn: "我们资金紧张，因为我们的客户要等薄膜用完才付款。" },
          { sp: "B", en: "Then let us meet halfway: 30% deposit, 40% against copy B/L, and 30% at 30 days after B/L date.", cn: "那我们各让一步：30% 定金，40% 见提单副本付，30% 提单日后 30 天付。" },
          { sp: "A", en: "Can you make the deposit 20% and give us 45 days for the last part?", cn: "定金能否降到 20%，最后一笔给我们 45 天？" },
          { sp: "B", en: "The deposit has to stay at 30% because the resin and solvent are bought against your order.", cn: "定金必须保持 30%，因为树脂和溶剂是按您的订单专门采购的。" },
          { sp: "A", en: "Understood. And when exactly will you start production?", cn: "明白了。那你们究竟什么时候开始生产？" },
          { sp: "B", en: "Production is scheduled from the day the deposit is credited to our account, not from the PI date.", cn: "排产从定金入账当天算起，而不是从形式发票日期算起。" },
          { sp: "A", en: "Fine. If we pay the 40% on the day we get the copy B/L, when do we get the originals?", cn: "可以。如果我们在收到提单副本当天付 40%，什么时候能拿到正本？" },
          { sp: "B", en: "We courier the originals the same afternoon and send you the tracking number by email.", cn: "我们当天下午就快递正本，并把快递单号邮件发给您。" },
          { sp: "A", en: "Then please revise the PI with these terms, and I will arrange the deposit tomorrow morning.", cn: "那请按这些条件修改形式发票，我明天上午安排定金。" },
          { sp: "B", en: "I will send the revised PI within an hour, with the 30-day part clearly tied to the B/L date.", cn: "我一小时内发出修改后的形式发票，并明确 30 天那笔以提单日为起算日。" }
        ]
      },
      {
        title: "信用证软条款与不符点交涉（L/C Discrepancies and Soft Clauses）",
        lines: [
          { sp: "A", en: "We received your L/C this morning, but two clauses make it impossible for us to get paid safely.", cn: "我们今天上午收到了您的信用证，但有两条条款使我们无法安全收款。" },
          { sp: "B", en: "Which clauses do you mean? Our bank says the credit follows the standard wording.", cn: "您指哪两条？我们银行说这份信用证用的是标准措辞。" },
          { sp: "A", en: "Field 46A requires an inspection certificate signed by the applicant, which is a typical soft clause.", cn: "46A 场要求提供开证申请人签署的检验证书，这是典型的软条款。" },
          { sp: "B", en: "We only want proof that the pouch thickness is 120 microns; let SGS issue it at your factory then. What is the second clause?", cn: "我们只是想确认包装袋厚度是 120 微米，那就让 SGS 在你方工厂出证吧。第二条是什么？" },
          { sp: "A", en: "One full set of original bills of lading is to be sent directly to you, leaving only two copies to the bank.", cn: "条款要求整套正本提单直接寄给您，只留两份副本给银行。" },
          { sp: "B", en: "Our customs broker asked for that to speed up clearance in Rotterdam.", cn: "我们的报关行为加快鹿特丹清关才这样要求的。" },
          { sp: "A", en: "If you hold the originals, you can take delivery even if the bank refuses payment. Please amend it to three-thirds to the bank.", cn: "如果正本在您手上，即使银行拒付您也能提货。请改为三分之三正本交银行。" },
          { sp: "B", en: "All right, I will apply for both amendments today. Anything else?", cn: "好的，我今天就申请这两项修改。还有别的吗？" },
          { sp: "A", en: "Yes, the latest shipment date is 15 May but the credit validity is also 15 May, leaving no time for presentation.", cn: "有，最迟装运期是 5 月 15 日，而信用证有效期也是 5 月 15 日，没有交单时间。" },
          { sp: "B", en: "So you need the expiry date extended. How long?", cn: "所以你们需要延长有效期。要多久？" },
          { sp: "A", en: "Please extend the validity to 5 June and allow presentation within 21 days after shipment.", cn: "请把有效期延至 6 月 5 日，并允许装运后 21 天内交单。" },
          { sp: "B", en: "Noted. By the way, last shipment the bank found discrepancies. What exactly went wrong?", cn: "记下了。顺便问一下，上批货银行发现了不符点，究竟是哪里出了问题？" },
          { sp: "A", en: "The invoice said aluminium foil pouch while the credit said alu foil pouch, and the gross weight differed by 12 kilos.", cn: "发票写的是 aluminium foil pouch，而信用证写的是 alu foil pouch，且毛重差了 12 公斤。" },
          { sp: "B", en: "I see. This time we will copy the description from the contract word for word so no discrepancy arises.", cn: "明白了。这次我们会逐字照抄合同上的品名描述，以免再出不符点。" }
        ]
      }
    ],
    tips: [
      "定金铁律：定金未到账，不排产、不下生产计划单、不订原纸原膜。汇款截图、银行受理回单、口头承诺都不算到账，必须由财务确认外币已入我方账户并核对金额与币种。客户催交期时，把「排产自定金入账日起算」写进形式发票，避免因等款压缩生产周期，最后还要背延期交货的责任。",
      "T/T 的风险几乎全在尾款：30% 定金加 70% 见提单副本付款看似安全，但开船后货已在途，主动权已经转移。规范做法是船开后先把提单副本、发票、箱单扫描件发客户催尾款，尾款到账再寄正本提单或申请电放。尾款未清绝不电放、绝不寄单，否则客户凭正本提货后完全可以无限期拖欠。",
      "信用证收到当天就要逐条与形式发票比对，重点排查软条款：买方签署的检验证书、货代或船公司由买方指定、正本提单直接寄买方、生效条件另行通知等，这些都把付款主动权交回买家。同时核实开证行资信与所在国风险、信用证有效期、最迟装运期和交单期（通常装船后 21 天内），发现问题立即要求改证，不要边生产边等改证。",
      "D/P 与 D/A 的风险差异要讲清：D/P 付款交单，客户不付款就拿不到单据，货权仍在我方，最坏结果是货到目的港转卖或退运；D/A 承兑交单，客户只要在汇票上承兑即可取得全套单据提货，到期付不付款全靠信用，等于无担保赊销。新客户一律不接 D/A，D/P 也要控制单笔金额，远期最好不超过 30 天。",
      "赊销和大额订单在报价前就要做资信调查：查企业注册年限、股东背景、涉诉与破产记录，可用中信保资信报告、邓白氏编码、当地商会和同行反馈交叉验证。凡以 O/A 或 D/A 成交的，必须投保出口信用保险，并严格在核定信用限额内发货，超限额部分改为电汇预付；一旦逾期，按保单规定的报损时限内申报，逾期申报会失去索赔权。",
      "单单一致是结汇的生命线：发票、箱单、提单、原产地证上的品名、规格、数量、净重毛重、唛头必须与合同和信用证逐字一致，复膜胶的牌号、薄膜的克重与卷数、包装袋的尺寸都不能有出入。一个字母或一公斤的差错就构成不符点，银行有权拒付并扣不符点费，改单重寄还会拖延结汇与出口退税进度。"
    ]
  });
})();
